
export let sortData = [
	{
		name: "Gabriel Hawkins",
		phone: "1-233-224-6123",
		email: "vel.venenatis@nuncrisus.ca",
		address: "Ap #995-3622 Curabitur Av.",
		postalZip: "432953",
		region: "Dolnośląskie",
		country: "Canada",
		list: 17,
		text: "odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa.",
		numberrange: 0,
		currency: "$62.53",
		alphanumeric: "OCH49YHU1PU"
	},
	{
		name: "Sasha Bishop",
		phone: "(398) 216-1564",
		email: "libero.integer@scelerisquemollis.net",
		address: "Ap #897-1027 Morbi Ave",
		postalZip: "99247",
		region: "Córdoba",
		country: "Germany",
		list: 17,
		text: "ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget",
		numberrange: 3,
		currency: "$95.30",
		alphanumeric: "GIX64RQE7ZU"
	},
	{
		name: "Hadley Hutchinson",
		phone: "1-543-424-1086",
		email: "lacinia.sed.congue@sociisnatoque.co.uk",
		address: "Ap #985-7044 Vel Rd.",
		postalZip: "10508",
		region: "Östergötlands län",
		country: "Chile",
		list: 9,
		text: "in lobortis tellus justo sit amet nulla. Donec non justo.",
		numberrange: 3,
		currency: "$60.78",
		alphanumeric: "AEP43ZIT6CG"
	},
	{
		name: "Ferris Abbott",
		phone: "(679) 491-5326",
		email: "mauris@sodalespurusin.co.uk",
		address: "P.O. Box 264, 5785 A, Road",
		postalZip: "05433",
		region: "Aberdeenshire",
		country: "Colombia",
		list: 9,
		text: "et ultrices posuere cubilia Curae Phasellus ornare. Fusce mollis. Duis",
		numberrange: 1,
		currency: "$72.56",
		alphanumeric: "CQK03RVC2GF"
	},
	{
		name: "Sonia Welch",
		phone: "(916) 892-6646",
		email: "eu.tempor.erat@suspendissecommodotincidunt.com",
		address: "587-8561 Pede Road",
		postalZip: "6641",
		region: "Vaupés",
		country: "Spain",
		list: 17,
		text: "cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut,",
		numberrange: 3,
		currency: "$12.30",
		alphanumeric: "MRH10WRW5KG"
	},
	{
		name: "Guy Langley",
		phone: "(421) 852-7543",
		email: "sed.dictum@utnulla.com",
		address: "913-9029 Ullamcorper. Ave",
		postalZip: "19464",
		region: "Antwerpen",
		country: "Poland",
		list: 17,
		text: "dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis",
		numberrange: 3,
		currency: "$84.89",
		alphanumeric: "FIE26UDQ8SV"
	},
	{
		name: "Cassandra Pennington",
		phone: "1-811-676-6536",
		email: "augue@donec.ca",
		address: "P.O. Box 490, 7070 Nulla Ave",
		postalZip: "5975",
		region: "Casanare",
		country: "New Zealand",
		list: 19,
		text: "erat, eget tincidunt dui augue eu tellus. Phasellus elit pede,",
		numberrange: 7,
		currency: "$77.55",
		alphanumeric: "NLB88MMX9CB"
	},
	{
		name: "Price Delaney",
		phone: "(844) 413-3741",
		email: "eu.placerat@enim.net",
		address: "Ap #203-7084 Convallis Rd.",
		postalZip: "96518",
		region: "Aquitaine",
		country: "New Zealand",
		list: 11,
		text: "augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna",
		numberrange: 6,
		currency: "$15.70",
		alphanumeric: "CQB22ZGZ0NS"
	},
	{
		name: "Ross Chambers",
		phone: "1-231-712-3333",
		email: "torquent.per@per.edu",
		address: "816-8268 Molestie Road",
		postalZip: "V4Z 9SU",
		region: "Alberta",
		country: "Belgium",
		list: 9,
		text: "lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,",
		numberrange: 6,
		currency: "$49.94",
		alphanumeric: "OFV12TQM2CQ"
	},
	{
		name: "James James",
		phone: "(655) 839-5167",
		email: "metus.aenean@sit.ca",
		address: "291-2069 Nisi. Av.",
		postalZip: "Z5 4MW",
		region: "Yukon",
		country: "Canada",
		list: 9,
		text: "elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec",
		numberrange: 5,
		currency: "$52.39",
		alphanumeric: "RZF24YSC7ET"
	},
	{
		name: "Jaden Martinez",
		phone: "(841) 920-2812",
		email: "aliquam.nisl@enimmauris.ca",
		address: "Ap #864-345 Egestas Avenue",
		postalZip: "732278",
		region: "Norte de Santander",
		country: "India",
		list: 19,
		text: "Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec",
		numberrange: 10,
		currency: "$41.26",
		alphanumeric: "QXY11IWF7XG"
	},
	{
		name: "Kiona Figueroa",
		phone: "1-165-876-6231",
		email: "vivamus.non@necleomorbi.ca",
		address: "P.O. Box 311, 3066 Etiam Road",
		postalZip: "56664",
		region: "Balochistan",
		country: "Nigeria",
		list: 9,
		text: "urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus",
		numberrange: 4,
		currency: "$22.47",
		alphanumeric: "QJJ04FRG5FU"
	},
	{
		name: "Dane Ramirez",
		phone: "1-279-385-6717",
		email: "maecenas.malesuada.fringilla@vitaesemper.org",
		address: "434-3519 In, Rd.",
		postalZip: "66163",
		region: "Victoria",
		country: "Indonesia",
		list: 19,
		text: "semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In",
		numberrange: 7,
		currency: "$80.34",
		alphanumeric: "ZLG86XEI6GY"
	},
	{
		name: "Sandra Eaton",
		phone: "(737) 179-3352",
		email: "nulla.tincidunt@tincidunt.co.uk",
		address: "874-6132 Ultrices Rd.",
		postalZip: "26006",
		region: "West Bengal",
		country: "New Zealand",
		list: 5,
		text: "cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet",
		numberrange: 8,
		currency: "$91.59",
		alphanumeric: "XEY17BTF9IU"
	},
	{
		name: "Jocelyn Estrada",
		phone: "(406) 846-0071",
		email: "ullamcorper.velit.in@etmagnisdis.net",
		address: "552 Laoreet St.",
		postalZip: "L4 0KO",
		region: "Dalarnas län",
		country: "South Korea",
		list: 7,
		text: "odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam",
		numberrange: 2,
		currency: "$24.28",
		alphanumeric: "DXE82NPJ4YV"
	},
	{
		name: "Branden Joseph",
		phone: "(652) 957-7120",
		email: "vulputate.nisi.sem@famesac.org",
		address: "235-864 Ullamcorper. Av.",
		postalZip: "2563",
		region: "Jigawa",
		country: "Belgium",
		list: 7,
		text: "imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at",
		numberrange: 2,
		currency: "$43.41",
		alphanumeric: "DVD17GTR8TT"
	},
	{
		name: "Shellie Sullivan",
		phone: "(224) 746-5316",
		email: "nunc.interdum@suspendisse.org",
		address: "660-707 Ullamcorper, Rd.",
		postalZip: "3059",
		region: "South Island",
		country: "Pakistan",
		list: 11,
		text: "nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum",
		numberrange: 4,
		currency: "$36.48",
		alphanumeric: "CAM16GJU9IX"
	},
	{
		name: "Wynne Blair",
		phone: "(211) 146-8586",
		email: "in@velit.co.uk",
		address: "192-6706 Sapien. Rd.",
		postalZip: "45457",
		region: "Santa Catarina",
		country: "Nigeria",
		list: 15,
		text: "Donec est mauris, rhoncus id, mollis nec, cursus a, enim.",
		numberrange: 5,
		currency: "$69.72",
		alphanumeric: "MJP46LRM6JR"
	},
	{
		name: "Winter Randall",
		phone: "1-622-522-8810",
		email: "interdum.ligula.eu@quampellentesque.com",
		address: "Ap #249-1274 Dictum. Street",
		postalZip: "6375",
		region: "Dalarnas län",
		country: "Italy",
		list: 5,
		text: "inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In",
		numberrange: 7,
		currency: "$13.53",
		alphanumeric: "IPW89KSL0YW"
	},
	{
		name: "Kathleen Edwards",
		phone: "1-537-383-4057",
		email: "cras.convallis@enimcommodo.com",
		address: "P.O. Box 704, 6036 Orci, Street",
		postalZip: "17439",
		region: "South Chungcheong",
		country: "Germany",
		list: 15,
		text: "ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor.",
		numberrange: 10,
		currency: "$35.53",
		alphanumeric: "VUQ42JQW4ZE"
	},
	{
		name: "Emily Hughes",
		phone: "1-555-220-0463",
		email: "nulla.integer@diam.edu",
		address: "142-1676 Dis Av.",
		postalZip: "HK8 7JL",
		region: "Leinster",
		country: "Netherlands",
		list: 3,
		text: "pede, ultrices a, auctor non, feugiat nec, diam. Duis mi",
		numberrange: 4,
		currency: "$50.11",
		alphanumeric: "OEH50ZRA8TW"
	},
	{
		name: "Mikayla Herring",
		phone: "(721) 777-9585",
		email: "vehicula@auctor.edu",
		address: "Ap #103-3409 Nulla St.",
		postalZip: "5473",
		region: "Huila",
		country: "Poland",
		list: 17,
		text: "malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis",
		numberrange: 7,
		currency: "$37.43",
		alphanumeric: "QQX81PTO0AN"
	}
];